name: hello-world
on:
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'deploy to'
        required: true
        default: 'in'
        options:
        - in
        - us
        - stage
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
